<?php

namespace App\Controller;


use App\Entity\Annonce;
use App\Form\AnnonceFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class AnnonceController extends Controller
{
    /**
     * @Route("/annonceadd", name="annonceAdd")
     */
    public function add(Request $request, EntityManagerInterface $em)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $annonce = new Annonce();
        $form = $this->createForm(AnnonceFormType::class, $annonce)->add('Ajouter', SubmitType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em->persist($annonce);
            $em->flush();

            return $this->redirectToRoute("annonceUp");

        }

        return $this->render('annonce/annonceAdd.html.twig',
            ["form" => $form->createView()]);

    }

    /**
     * @Route("/annonceshow", name="annonceShow")
     */

    public function show()
    {

        return $this->render('annonce/annonceShow.html.twig');
    }

    /**
     * @Route("/annonceup",name="annonceUp")
     */
    public function annonceUp()
    {

        $em = $this->getDoctrine()->getManager();
        $annonces = $em->getRepository(Annonce::class)->findAll();

        dump($annonces);
        return $this->render('home/annonceUpToDate.html.twig', [

            'annonces' => $annonces
        ]);
    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


}
