<?php

namespace App\Controller;


use App\Entity\Annonce;
use App\Form\AnnonceFormType;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class AnnonceController extends Controller
{
    /**
     * @Route("/annonceadd", name="annonceadd")
     */
    public function add(Request $request, EntityManagerInterface $em, FileUploader $fileUploader)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $annonce = new Annonce();
        $form = $this->createForm(AnnonceFormType::class, $annonce)->add('Ajouter', SubmitType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $file = $annonce->getImage();
            $fileName = $fileUploader->upload($file);
            $annonce->setImage($fileName);

            $em->persist($annonce);
            $em->flush();

            return $this->redirectToRoute("annonceUp");

        }

        return $this->render('annonce/annonceAdd.html.twig',
            ["form" => $form->createView()]);

    }

    /**
     * @Route("/annonceshow/{id}", name="annonceshow")
     *
     */

    public function show(Annonce $annonce)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('annonce/annonceShow.html.twig', [

            'annonce' => $annonce
        ]);

    }

    /**
     * @Route("/annonceup",name="annonceup")
     */
    public function annonceUp()
    {

        $em = $this->getDoctrine()->getManager();
        $annonces = $em->getRepository(Annonce::class)->findAll();

        return $this->render('home/annonceUpToDate.html.twig', [

            'annonces' => $annonces
        ]);
    }
//METTRE A JOUR UNE ANNONCE
    /**
     * @Route('/annonce/update/{annonce}')
     */
    public function update_ann(Annonce $annonce)
    {
        $em = $this->getDoctrine()->getManager();
        $annonces = $em->getRepository(Annonce::class)->findAll();
        return ["annonces" => $annonces];

    }

    //SUPPRIMER UNE ANNONCE

    /**
     * @Route('/annonce/delete/{annonce}')
     */
    public function delete_ann(Annonce $annonce)
    {

        $em = $this->getDoctrine()->getManager();
        $annonces = $em->getRepository(Annonce::class)->findAll();
        return ["annonces" => $annonces];
    }






    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


}
